"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.USER_ACTION_REQUEST = 'USER_ACTION_REQUEST';
exports.USER_ACTION_FAILURE = 'USER_ACTION_FAILURE';
exports.USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
exports.USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
exports.USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
exports.USER_GET_SUCCESS = 'USER_GET_SUCCESS';
;
;
;
;
;
;
;
;
;
;
